### PR TITLE
chore: Update objectbox to 1.4.1

### PR DESCRIPTION
**Pull request by cmengler**
This PR bumps to the latest `objectbox` package with generated code (`flat_buffers` broken out into own package).

### CODE REVIEW

**Comment by llfbandit** [comment]
I can't publish the package because of flat_buffers package.

```
objectbox.g.dart: This package does not have flat_buffers in the `dependencies` section of `pubspec.yaml`.  
11 │ import 'package:flat_buffers/flat_buffers.dart' as fb;
```

**Comment by cmengler** [comment]
Ah -- this is the explicit version the `objectbox` package specifies for `1.4.1` in the `pubspec.yaml`:

``` 
flat_buffers: 2.0.5
```

**Comment by llfbandit** [comment]
Hmm ok, but why ObjectBox page does not mention it in README.md and doesn't reference it in example project?

**Comment by cmengler** [comment]
I was thinking the same thing, although I don't need to explicitly add `flat_buffers` to my project either.

The dependency pulls through on `dart pub get`, I'm guessing it's a requirement by pub.dev?

**Comment by llfbandit** [comment]
Not pub.dev explicitly but `dart pub publish --dry-run` which analyses the package before uploading.
I added `flat_buffers` as a direct dependency to workaround this and published the package.

**Pull request merged**
