### PR TITLE
fix: Update tests (#97)

### LINKED ISSUE #97: Ensure drift database isolate is closed
following up on #94:
in older drift versions, isolates must be explicitly closed.
however, I have asked upstream to implement an easy feature to close isolates when the single connection is closed.
by upgrading to drift 2.3.0 we can take advantage of this and shorten the isolate code by alot,
and make sure that users to not run into lingering database connections.

### PR DESCRIPTION
**Pull request by clragon**
Updates tests to remove `open.overrideFor` and `sqlite3` since they do not seem to be needed.
fix #97

### CODE REVIEW

**Comment by clragon** [comment]
tests have run through, but somehow uploading coverage to LCOV has failed, and therefore the runner died. 
I am not sure how to fix that.

**Comment by llfbandit** [comment]
`open.overrideFor` is needed on Windows. I guess you're on linux where sqlite is already installed.
For LCOV, there's a compatibility issue with codecov and dart output version.
I'll be back next week to handle those PRs.

**Comment by clragon** [comment]
I have run the test on windows and it didnt seem like it was needed. 
The other day I was also able to remove `sqlite3` from my application.
I believe some of the required files have been included in other libraries.

**Comment by llfbandit** [comment]
Thanks for the feedback.
I was still unable to correctly load the library when running tests.

Drift has been upgraded to 2.5 as minimum version.
Tests have been updated by downloading lib file from official site and moved to root folder to workaround the issue with `overrideFor` directive which is empty when running tests (see 3c9b8b1c).

**Pull request closed without merging**
